mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('potholedet.urls')),
    path('admin/', admin.site.urls),

]

mysite/potholedet/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'potholedet'

urlpatterns = [
    path('', views.index, name='index'),
    path('videotest/',
         views.videotest, name='videotest'),
    path('result/', views.result, name='result'),
    path('potholemap/', views.potholemap, name='potholemap'),
    path('about/', views.about, name='about'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/potholedet/models.py
from django.db import models

# Create your models here.


class Pothole(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()

mysite/potholedet/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
import cv2 as cv
import numpy as np
# Rest of your pothole detection code
# importing necessary libraries
import cv2 as cv
import time
import geocoder
import os
from django.conf import settings
# add these lines at the beginning of the script
import numpy as np

from .models import Pothole


def index(request) -> HttpResponse:
    return render(request, 'potholedet/index.html')


def videotest(request):
    if request.method == 'POST' and request.FILES.get('video'):
        video_file = request.FILES['video']
        video_path = os.path.join(settings.BASE_DIR, 'media', video_file.name)
        with open(video_path, 'wb') as f:
            for chunk in video_file.chunks():
                f.write(chunk)

        # reading label name from obj.names file
        class_name = []
        with open(os.path.join(settings.BASE_DIR, "project_files", 'obj.names'), 'r') as f:
            class_name = [cname.strip() for cname in f.readlines()]

        # importing model weights and config file
        # defining the model parameters
        net1 = cv.dnn.readNet(os.path.join(settings.BASE_DIR, 'project_files', 'yolov4_tiny.weights'),
                              os.path.join(settings.BASE_DIR, 'project_files', 'yolov4_tiny.cfg'))
        net1.setPreferableBackend(cv.dnn.DNN_BACKEND_CUDA)
        net1.setPreferableTarget(cv.dnn.DNN_TARGET_CUDA_FP16)
        model1 = cv.dnn_DetectionModel(net1)
        model1.setInputParams(size=(640, 480), scale=1/255, swapRB=True)

        # defining the video source (0 for camera or file name for video)
        cap = cv.VideoCapture(video_path)
        width = cap.get(3)
        height = cap.get(4)
        result_path = os.path.join(
            settings.BASE_DIR, 'potholedet', 'static', 'result.mp4')
        result = cv.VideoWriter(result_path,
                                cv.VideoWriter_fourcc(*'avc1'),
                                10, (int(width), int(height)))

        # defining parameters for result saving and get coordinates
        # defining initial values for some parameters in the script
        g = geocoder.ip('me')
        result_path = os.path.join(
            settings.BASE_DIR, 'pothole_coordinates')
        starting_time = time.time()
        Conf_threshold = 0.5
        NMS_threshold = 0.4
        frame_counter = 0
        i = 0
        b = 0

        # detection loop
        while True:
            ret, frame = cap.read()
            frame_counter += 1
            if ret == False:
                break

            # lane detection
            gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
            blurred = cv.GaussianBlur(gray, (5, 5), 0)
            edges = cv.Canny(blurred, 50, 150)
            roi = edges[300:480, 150:450]
            lines = cv.HoughLinesP(roi, rho=1, theta=1*np.pi/180,
                                   threshold=20, minLineLength=50, maxLineGap=5)
            if lines is not None:
                for line in lines:
                    x1, y1, x2, y2 = line[0]
                    cv.line(frame, (x1+150, y1+300),
                            (x2+150, y2+300), (0, 0, 255), 2)
            # analysis the stream with detection model
            classes, scores, boxes = model1.detect(
                frame, Conf_threshold, NMS_threshold)
            for (classid, score, box) in zip(classes, scores, boxes):
                label = "pothole"
                x, y, w, h = box
                recarea = w*h
                area = width*height
                # drawing detection boxes on frame for detected potholes and saving coordinates txt and photo
                if (len(scores) != 0 and scores[0] >= 0.7):
                    if ((recarea/area) <= 0.1 and box[1] < 600):
                        cv.rectangle(
                            frame, (x, y), (x + w, y + h), (0, 255, 0), 1)
                        cv.putText(frame, "%" + str(round(scores[0]*100, 2)) + " " + label,
                                   (box[0], box[1]-10), cv.FONT_HERSHEY_COMPLEX, 0.5, (255, 0, 0), 1)
                        if (i == 0):
                            cv.imwrite(os.path.join(
                                result_path, 'pothole'+str(i)+'.jpg'), frame)
                            with open(os.path.join(result_path, 'pothole'+str(i)+'.txt'), 'w') as f:
                                f.write(str(g.latlng))
                                i = i+1
                        if (i != 0):
                            if ((time.time()-b) >= 2):
                                cv.imwrite(os.path.join(
                                    result_path, 'pothole'+str(i)+'.jpg'), frame)
                                with open(os.path.join(result_path, 'pothole'+str(i)+'.txt'), 'w') as f:
                                    f.write(str(g.latlng))
                                    latitude, longitude = g.latlng
                                    pothole = Pothole(
                                        latitude=latitude, longitude=longitude)
                                    pothole.save()
                                    b = time.time()
                                    i = i+1

            # writing fps on frame
            endingTime = time.time() - starting_time
            fps = frame_counter/endingTime
            cv.putText(frame, f'FPS: {fps}', (20, 50),
                       cv.FONT_HERSHEY_COMPLEX, 0.7, (0, 255, 0), 2)
            # showing and saving result
            cv.imshow('frame', frame)
            result.write(frame)
            key = cv.waitKey(1)
            if key == ord('q'):
                break

        # end
        cap.release()
        result.release()
        cv.destroyAllWindows()

        # Return the processed video or display it on the page
        context = {'video_path': video_path}
        return render(request, 'potholedet/pages/result.html', context)

    return render(request, 'potholedet/pages/videotest.html')

    # add this function to the script


def detect_lanes(image):
    # convert image to grayscale
    gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)

    # apply Gaussian blur to reduce noise
    blur = cv.GaussianBlur(gray, (5, 5), 0)

    # detect edges using Canny edge detection algorithm
    edges = cv.Canny(blur, 50, 150)

    # define a region of interest (ROI)
    height, width = edges.shape
    roi = np.array([[(0, height), (width // 2, height // 2),
                     (width, height), (0, height)]], dtype=np.int32)

    # apply ROI mask to the edges image
    masked_edges = np.zeros_like(edges)
    cv.fillPoly(masked_edges, roi, 255)
    masked_edges = cv.bitwise_and(edges, masked_edges)

    # detect lines using Hough line transform
    lines = cv.HoughLinesP(masked_edges, rho=2, theta=np.pi/180,
                           threshold=50, minLineLength=50, maxLineGap=100)

    # draw detected lines on the original image
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv.line(image, (x1, y1), (x2, y2), (0, 0, 255), 2)

    return image


def result(request):
    # Process any necessary data or calculations
    # ...

    video_path = os.path.join(settings.BASE_DIR, 'media', 'result.mp4')

    # Render the result page with the video path
    return render(request, 'potholedet/pages/result.html', {'video_path': video_path})


def potholemap(request):
    potholes = Pothole.objects.all()
    coordinates = [(pothole.latitude, pothole.longitude)
                   for pothole in potholes]

    context = {'coordinates': coordinates}
    return render(request, 'potholedet/pages/potholemap.html', context)


def about(request):
    return render(request, 'potholedet/pages/about.html')

mysite/potholedet/templates/potholedet/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Brand</title>
    <link
      rel="stylesheet"
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
    />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-md sticky-top navbar-shrink py-3" id="mainNav">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="/"><span class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex justify-content-center align-items-center me-2 bs-icon"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-bezier">
                        <path fill-rule="evenodd" d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5v-1zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"></path>
                        <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5v-1zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z"></path>
                    </svg></span><span>Errnesto</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item"><a class="nav-link active" href="{% url 'potholedet:index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'potholedet:potholemap'%}">Pothole Maps</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'potholedet:videotest' %}">Video Test</a></li>
                    <li class="nav-item"> <a  class="nav-link" href="{% url 'potholedet:result' %}"> Results </a></li>
                    <li class="nav-item"></li>
                </ul><a class="btn btn-primary shadow" role="button" href="{% url 'potholedet:about' %}">About</a>
            </div>
        </div>
    </nav>
    <div class="container">

    {% block content %} {% endblock %}
    </div>
    <footer>
        <div class="container text-center bg-primary-gradient">
            <p>Apxb08© 2023</p>
        </div>
    </footer>
  
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bold-and-bright.js' %}"></script>

    {% block script %}
    
    {% endblock %}
</body>

</html>

mysite/potholedet/templates/potholedet/index.html
{% extends 'potholedet/base.html' %}
{% load static %}
{% block content %}
<header class="bg-primary-gradient">
  <div class="container pt-4 pt-xl-5">
      <div class="row pt-5">
          <div class="col-md-8 col-xl-6 text-center text-md-start mx-auto">
              <div class="text-center">
                  <p class="fw-bold text-success mb-2">Ernesto&nbsp; Pothole Detection</p>
                  <h1 class="fw-bold">Pothole Detection System</h1>
              </div>
          </div>
          <div class="col-12 col-lg-10 mx-auto">
              <div class="position-relative" style="display: flex;flex-wrap: wrap;justify-content: flex-end;">
                  <div style="position: relative;flex: 0 0 45%;transform: translate3d(-15%, 35%, 0);"><img class="img-fluid" data-bss-parallax="" data-bss-parallax-speed="0.8" src="{% static 'img/products/potholeimage.jpg' %}"></div>
                  <div style="position: relative;flex: 0 0 45%;transform: translate3d(-5%, 20%, 0);"><img class="img-fluid" data-bss-parallax="" data-bss-parallax-speed="0.4" src="{% static 'img/products/workers-placing-new-coating-asphalt-road.jpg' %}"></div>
                  <div style="position: relative;flex: 0 0 60%;transform: translate3d(0, 0%, 0);"><img class="img-fluid" data-bss-parallax="" data-bss-parallax-speed="0.25" src="{% static 'img/products/close-up-orange-traffic-cone-road-copy-space.jpg' %}"></div>
              </div>
          </div>
      </div>
  </div>
</header>
{% endblock %}

mysite/potholedet/templates/potholedet/pages/about.html
{% extends 'potholedet/base.html' %}
{% load static %}

{% block content %}
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6" style="
      overflow: hidden;
  ">
        <img src="{% static 'img/Roadworks Image.jpg' %}" alt="Pothole Detection Software">
      </div>
      <div class="col-lg-6">
        <h2>Pothole Detection Software</h2>
        <p>The Pothole Detection Software is an innovative solution for identifying and mapping potholes in road surfaces. It utilizes advanced computer vision algorithms to analyze images or videos captured by cameras or drones to detect and locate potholes accurately.</p>
        <p>The software employs state-of-the-art machine learning techniques, specifically object detection, to identify potholes within the captured images or videos. It can efficiently process large volumes of data and generate real-time insights for road maintenance and repair planning.</p>
        <p>Key Features:</p>
        <ul>
          <li>Accurate detection and location of potholes</li>
          <li>Support for image and video analysis</li>
          <li>Real-time monitoring and reporting</li>
          <li>Heatmap visualization for pothole distribution</li>
          <li>Data export and integration with other systems</li>
        </ul>
        <p>With the Pothole Detection Software, road authorities and maintenance teams can efficiently identify and prioritize pothole repairs, ensuring safer and well-maintained road networks for the community.</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

mysite/potholedet/templates/potholedet/pages/potholemap.html
{% extends 'potholedet/base.html' %}
{% load static %}

{% block content %}
<section class="py-5">
  <div class="container py-5">
      <div class="row mb-4 mb-lg-5">
          <div class="col-md-8 col-xl-6 text-center mx-auto">
              <p class="fw-bold text-success mb-2">Local</p>
              <h3 class="fw-bold">Pothole Maps in Zimbabwe</h3>
              <div id="map" style="height: 600px; width: 100%;"></div>
          </div>
      </div>
  </div>
</section>
{% endblock %}

{% block script %}
<script src="https://polyfill.io/v3/polyfill.js?features=default"></script>
<script>
    function initMap() {
        var mapOptions = {
            zoom: 12,
            center: { lat: -20.157, lng: 28.583 },
            mapTypeId: 'roadmap',
            styles: [
                // Customize the map styling here
                // You can find different styles from the Google Maps API documentation or other sources
            ]
        };

        var map = new google.maps.Map(document.getElementById('map'), mapOptions);

        var heatmapData = [
            {% for coordinate in coordinates %}
            new google.maps.LatLng({{ coordinate.0 }}, {{ coordinate.1 }}),
            {% endfor %}
        ];

        var heatmap = new google.maps.visualization.HeatmapLayer({
          data: heatmapData,
          dissipating: true,
          map: map
      });
      


    }
</script>

    <script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDGpHozG4LVQn1pzqAbp3d8CtLPv0kqbas&libraries=visualization&callback=initMap">
    </script>
{% endblock%}

mysite/potholedet/templates/potholedet/pages/result.html
{% extends 'potholedet/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Pothole Detection Result</h1>
    <div id="video-player">
        
    </div>
</div>
{% endblock %}

{% block script %}
<script>

    document.addEventListener("DOMContentLoaded", function() {
        // Get the video player div
        var videoPlayer = document.getElementById("video-player");
    
        // Create the video element
        var videoElement = document.createElement("video");
        videoElement.controls = true;
    
        // Create the source element and set the source URL
        var sourceElement = document.createElement("source");
        sourceElement.src = "{% static 'result.mp4' %}"; // Change 'result.mp4' to the correct path of your video file
    
        // Append the source element to the video element
        videoElement.appendChild(sourceElement);
    
        // Append the video element to the video player div
        videoPlayer.appendChild(videoElement);
    });
</script>
{% endblock %}

mysite/potholedet/templates/potholedet/pages/videotest.html
{% extends 'potholedet/base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <h1>Video Test</h1>
  <form method="post" enctype="multipart/form-data" action="{% url 'potholedet:videotest' %}">
      {% csrf_token %}
      <div class="mb-3">
          <input type="file" name="video" class="form-control">
      </div>
      <button type="submit" class="btn btn-primary">Upload and Detect Potholes</button>
  </form>
</div>
{% endblock %}